name: Update README with IPython Notebook List

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get file list
        run: |
          ls > file_list.txt
          cat file_list.txt

