name: Update README with IPython Notebook List

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get file list
        run: |
          ls *.ipynb > file_list.txt
          echo "::set-output name=file_list::$(cat file_list.txt)"
        shell: bash
      - name: Update README
        run: |
          echo "# Hero Colabs" > README.md
          file=1
          while read line; do
            dir=$(dirname "$line")
            filename=$(basename "$line")
            filename="${filename%.ipynb}"  # remove the extension
            file_name=$filename
            filename="${filename//_/ }"  # replace underscore with space
            acronym=$(echo "$filename" | awk '{for(i=1;i<=NF;i++){printf "%s",toupper(substr($i,1,1))}}')
            colab_url="https://colab.research.google.com/github/HeroBenHero/HeroColabs/blob/main/$line"
            echo "## [$filename]($line) &nbsp;&nbsp; [![Open in Colab][Colab Badge]][$acronym]" >> README.md
            echo "[$acronym]:https://github.com/HeroBenHero/HeroColabs/tree/main/$line" >> README.md
            ((file++))
          done < file_list.txt
          echo "" >> README.md
          echo "[Colab Badge]:https://colab.research.google.com/assets/colab-badge.svg" >> README.md
          cat README.md
        shell: bash
      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md"
          commit_options: "--no-verify"
          file_pattern: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
