name: Update README with IPython Notebook List

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get file list
        run: |
          ls *.ipynb > file_list.txt
          echo "::set-output name=file_list::$(cat file_list.txt)"
        shell: bash
      - name: Update README
        run: |
          echo "# Hero Colabs" > README.md
          while read line; do
            dir=$(dirname "$line")
            filename=$(basename "$line")
            colab_url="https://colab.research.google.com/github/HeroBenHero/HeroColabs/blob/main/$line"
            echo "## [$dir](https://github.com/HeroBenHero/HeroColabs/tree/main/$dir) &nbsp;&nbsp; [![Open in Colab][Colab Badge]][$dir]" >> README.md
            echo "[$dir]: $colab_url" >> README.md
          done < file_list.txt
          echo "" >> README.md
          cat README.md
        shell: bash
      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md"
          commit_options: "--no-verify"
          file_pattern: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
